### ISSUE TITLE
Add teddit support

### ISSUE THREAD

**Issue by tunbridgep** [aledeg/xExtension-RedditImage#6]
The plugin should have an optional "use teddit" checkbox. When checked, all reddit feeds will automatically display content from teddit.net instead of reddit.com. Regardless of the checkbox setting, any feed displaying content from teddit.net should include all the correct image embeds as it would for reddit

**Comment by aledeg** [comment]
It's a great idea but do you know how teddit feeds are working? I've tried to convert reddit feeds to teddit feeds without success.
If you have some pointers, I'd be happy to figure something out.

**Comment by aledeg** [comment]
I've found how to generate the RSS but its content is useless since there is no link to the media. If you find a way to get it, it will be quite easy to fetch the content and display it as it is with reddit feeds.

I think it's a teddit bug because the link directs to the comments section. I think you should first open an issue with teddit.

**Comment by aledeg** [comment]
I've opened an issue on teddit repository. It can be found [here](https://codeberg.org/teddit/teddit/issues/347).

**Comment by aledeg** [comment]
@tunbridgep Maybe you can add some weight on the opened issue on teddit

**Comment by aledeg** [comment]
@tunbridgep teddit is closing on August 1st. Do you plan to host it yourself?

**Comment by aledeg** [comment]
@tunbridgep Feel free to reopen it if need. I think we can close it for now.

**Comment by sarge945** [comment]
Yeah, turns out Teddit died a death. It's a real shame, but that's how it goes sometimes. This definitely isn't relevant anymore, thanks for closing.
